services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    # entrypoint: ["sleep", "infinity"]
     # -m /models/sarvam-translate.Q3_K_M.gguf
     # -m /models/Apertus-8B-2509.Q4_K_M.gguf
    command: >
      -m ${MODEL_PATH}
      --port 8080
      --host 0.0.0.0
      -n 512
      -fa on
    volumes:
      - ./models:/models
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              #device_ids: ['0']
